[project]
name = "attestable-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ryan MacArthur", email = "ryan.macarthur@gmail.com" }
]
requires-python = ">=3.13"

dependencies = [
    "anyio>=4.5",
    "httpx>=0.27",
    "httpx-sse>=0.4",
    "pydantic>=2.7.2,<3.0.0",
    "starlette>=0.27",
    "sse-starlette>=1.6.1",
    "pydantic-settings>=2.5.2",
    "uvicorn>=0.23.1",
    "docker>=7.1.0",
    "jinja2>=3.1.6",
    "tomli>=2.2.1",
    "tomli-w>=1.2.0",
    "pyyaml>=6.0.2",
    "fastapi[standard]>=0.115.12",
    "google-api-python-client>=2.176.0",
    "google-auth>=2.40.3",
    "google-auth-oauthlib>=1.2.2",
    "mcp>=1.11.0",
]


[project.scripts]
attestable-mcp-server = "attestable_mcp_server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.uv]
dev-dependencies = ["pyright>=1.1.378", "pytest>=8.3.3", "ruff>=0.6.9"]

